version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: aplication
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity